#########################################################################
# Title:         Cloudbox: System | Mounts Tasks                        #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: System | Display system mounts
  debug:
    msg: "{{ ansible_mounts }}"

- name: System | Set opts for '/' ext4 mount
  mount:
    path: /
    opts: defaults,noatime,nobarrier
    state: present
    fstype: ext4
    src: "{{ item.device }}"
  with_items:
    - "{{ ansible_mounts }}"
  when: (item.mount == '/') and (item.fstype == 'ext4')
