#########################################################################
# Title:         Cloudbox: Remote | Fuse Tasks                          #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Fuse | Install fuse"
  apt:
    name: fuse
    state: present

- name: "Fuse | Import 'fuse.conf'"
  copy: src=fuse.conf dest=/etc/fuse.conf force=no mode=0775
